import 'package:flutter/material.dart';
import 'package:table_calendar/table_calendar.dart';
import '../models/models.dart';
import '../services/database_service.dart';
import '../utils/utils.dart';
import 'screens.dart';

class CalendarScreen extends StatefulWidget {
  const CalendarScreen({super.key});

  @override
  State<CalendarScreen> createState() => _CalendarScreenState();
}

class _CalendarScreenState extends State<CalendarScreen> {
  DateTime _focusedDay = DateTime.now();
  DateTime? _selectedDay;
  Map<DateTime, List<Visit>> _visitsByDay = {};
  List<Visit> _selectedVisits = [];
  bool _startWeekOnMonday = false;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _selectedDay = DateTime.now();
    _loadVisits();
  }

  Future<void> _loadVisits({DateTime? focusedDay}) async {
    final focus = focusedDay ?? _focusedDay;
    final from = DateTime(focus.year, focus.month - 3, 1);
    final to = DateTime(focus.year, focus.month + 4, 0, 23, 59, 59);
    final visits = await DatabaseService.getVisits(from: from, to: to);
    final startWeekOnMonday =
        await DatabaseService.getSetting('start_calendar_week_on_monday') ==
            'true';
    final map = <DateTime, List<Visit>>{};

    for (final visit in visits) {
      final day = DateTime(
        visit.dateTime.year,
        visit.dateTime.month,
        visit.dateTime.day,
      );
      map.putIfAbsent(day, () => []).add(visit);
    }

    if (mounted) {
      setState(() {
        _visitsByDay = map;
        _selectedVisits = _getVisitsForDay(_selectedDay!);
        _startWeekOnMonday = startWeekOnMonday;
        _loading = false;
      });
    }
  }

  List<Visit> _getVisitsForDay(DateTime day) {
    final normalized = DateTime(day.year, day.month, day.day);
    return _visitsByDay[normalized] ?? [];
  }

  void _onDaySelected(DateTime selectedDay, DateTime focusedDay) {
    setState(() {
      _selectedDay = selectedDay;
      _focusedDay = focusedDay;
      _selectedVisits = _getVisitsForDay(selectedDay);
    });
  }

  Future<void> _confirmVisit(Visit visit) async {
    await DatabaseService.confirmAutoGeneratedVisit(visit.id!);
    await _loadVisits();
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Appointment confirmed')),
    );
  }

  Widget _buildMarkers(BuildContext context, DateTime day, List<Visit> events) {
    if (events.isEmpty) return const SizedBox.shrink();

    final primary = Theme.of(context).colorScheme.primary;
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: events.take(4).map((visit) {
        return Container(
          width: 7,
          height: 7,
          margin: const EdgeInsets.symmetric(horizontal: 1),
          decoration: BoxDecoration(
            color: visit.isAutoGenerated ? Colors.transparent : primary,
            shape: BoxShape.circle,
            border: visit.isAutoGenerated
                ? Border.all(color: primary, width: 1.2)
                : null,
          ),
        );
      }).toList(),
    );
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return Scaffold(
        appBar: AppBar(title: const Text('Calendar')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    return Scaffold(
      appBar: AppBar(title: const Text('Calendar')),
      body: Column(
        children: [
          TableCalendar<Visit>(
            firstDay: DateTime(2020),
            lastDay: DateTime(2035),
            focusedDay: _focusedDay,
            startingDayOfWeek: _startWeekOnMonday
                ? StartingDayOfWeek.monday
                : StartingDayOfWeek.sunday,
            selectedDayPredicate: (day) => isSameDay(_selectedDay, day),
            onDaySelected: _onDaySelected,
            onPageChanged: (focusedDay) {
              _focusedDay = focusedDay;
              _loadVisits(focusedDay: focusedDay);
            },
            eventLoader: (day) => _getVisitsForDay(day),
            calendarBuilders: CalendarBuilders(
              markerBuilder: _buildMarkers,
            ),
            calendarStyle: CalendarStyle(
              markerDecoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primary,
                shape: BoxShape.circle,
              ),
              todayDecoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primaryContainer,
                shape: BoxShape.circle,
              ),
              selectedDecoration: BoxDecoration(
                color: Theme.of(context).colorScheme.primary,
                shape: BoxShape.circle,
              ),
            ),
            headerStyle: const HeaderStyle(
              formatButtonVisible: false,
              titleCentered: true,
            ),
          ),
          const Divider(height: 1),
          Expanded(
            child: _selectedVisits.isEmpty
                ? Center(
                    child: Text(
                      'No visits on ${AppUtils.formatDate(_selectedDay!)}',
                      style: Theme.of(context).textTheme.bodyLarge,
                    ),
                  )
                : ListView.builder(
                    itemCount: _selectedVisits.length,
                    itemBuilder: (_, i) {
                      final visit = _selectedVisits[i];
                      return VisitListTile(
                        visit: visit,
                        onConfirm: visit.isAutoGenerated
                            ? () => _confirmVisit(visit)
                            : null,
                        onTap: () async {
                          await Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (_) => VisitDetailScreen(visit: visit),
                            ),
                          );
                          _loadVisits();
                        },
                      );
                    },
                  ),
          ),
        ],
      ),
    );
  }
}
