import 'dart:async';
import 'dart:io';
import 'package:add_2_calendar/add_2_calendar.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';
import '../l10n/generated/app_localizations.dart';
import '../models/models.dart';
import '../services/database_service.dart';
import '../services/invoice_service.dart';
import '../utils/utils.dart';
import '../widgets/widgets.dart';
import 'screens.dart';

class VisitDetailScreen extends StatefulWidget {
  final Visit visit;
  const VisitDetailScreen({super.key, required this.visit});

  @override
  State<VisitDetailScreen> createState() => _VisitDetailScreenState();
}

class _VisitDetailScreenState extends State<VisitDetailScreen> {
  late Visit _visit;
  Client? _client;
  List<Horse> _horses = [];
  List<ServiceLine> _serviceLines = [];
  List<VisitCharge> _charges = [];
  List<VisitPhoto> _photos = [];
  List<InvoiceRecord> _invoices = [];
  bool _loading = true;

  late TextEditingController _invoiceNotesCtrl;
  Timer? _notesSaveTimer;

  @override
  void initState() {
    super.initState();
    _visit = widget.visit;
    _invoiceNotesCtrl = TextEditingController(text: _visit.notes);
    _loadData();
  }

  @override
  void dispose() {
    _notesSaveTimer?.cancel();
    _invoiceNotesCtrl.dispose();
    super.dispose();
  }

  Future<void> _loadData() async {
    final visit = await DatabaseService.getVisit(_visit.id!);
    final horses = await DatabaseService.getHorsesForVisit(_visit.id!);
    final serviceLines = await DatabaseService.getServiceLines(_visit.id!);
    final charges = await DatabaseService.getVisitCharges(_visit.id!);
    final photos = await DatabaseService.getPhotos(_visit.id!);
    final invoices = await DatabaseService.getInvoicesForVisit(_visit.id!);
    final client = await DatabaseService.getClient(_visit.clientId);
    if (mounted) {
      setState(() {
        if (visit != null) {
          _visit = visit;
          // Sync the text controller if user isn't actively editing
          if (!_invoiceNotesCtrl.text.contains(visit.notes) ||
              _invoiceNotesCtrl.text == _visit.notes) {
            _invoiceNotesCtrl.removeListener(_scheduleNotesSave);
            _invoiceNotesCtrl.text = visit.notes;
            _invoiceNotesCtrl.addListener(_scheduleNotesSave);
          }
        }
        _client = client;
        _horses = horses;
        _serviceLines = serviceLines;
        _charges = charges;
        _photos = photos;
        _invoices = invoices;
        _loading = false;
      });
    }
  }

  void _scheduleNotesSave() {
    _notesSaveTimer?.cancel();
    _notesSaveTimer = Timer(const Duration(milliseconds: 800), () async {
      await DatabaseService.updateVisitNotes(_visit.id!, _invoiceNotesCtrl.text);
      if (mounted) {
        setState(() {
          _visit = _visit.copyWith(notes: _invoiceNotesCtrl.text);
        });
      }
    });
  }

  double get _serviceLinesTotal =>
      _serviceLines.fold(0.0, (sum, line) => sum + line.lineTotal);
  double get _chargesTotal => _charges.fold(0.0, (sum, c) => sum + c.total);
  double get _total => _serviceLinesTotal + _chargesTotal;

  Future<void> _togglePaid(bool value) async {
    final wasPaid = _visit.paid;
    await DatabaseService.setVisitPaid(_visit.id!, value);
    await DatabaseService.setInvoicesPaidForVisit(_visit.id!, value);
    setState(() {
      _visit = _visit.copyWith(paid: value);
    });
    if (!mounted) return;
    if (!wasPaid &&
        value &&
        _visit.recurrenceWeeks != null &&
        _visit.nextRecurringVisitId == null) {
      final l10n = AppLocalizations.of(context)!;
      final scheduleNext = await ConfirmationDialog.show(
        context,
        title: l10n.recurringVisitTitle,
        message: l10n.scheduleNextRecurringVisit,
      );
      if (scheduleNext == true) {
        await DatabaseService.generateRecurringChain(_visit, weeksAhead: 10);
      }
    }
    _loadData();
  }

  Future<void> _toggleCompleted(bool value) async {
    await DatabaseService.setVisitCompleted(_visit.id!, value);
    setState(() {
      _visit = _visit.copyWith(completed: value);
    });
  }

  Future<void> _confirmProjectedVisit() async {
    await DatabaseService.confirmAutoGeneratedVisit(_visit.id!);
    await _loadData();
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(AppLocalizations.of(context)!.appointmentConfirmedSnackbar)),
    );
  }

  Future<void> _addServiceLine() async {
    final result = await showDialog<ServiceLine>(
      context: context,
      builder: (_) => ServiceLineDialog(
        visitId: _visit.id!,
        horses: _horses,
      ),
    );
    if (result != null) {
      await DatabaseService.insertServiceLine(result);
      _loadData();
    }
  }

  Future<void> _editServiceLine(ServiceLine line) async {
    final result = await showDialog<ServiceLine>(
      context: context,
      builder: (_) => ServiceLineDialog(
        visitId: _visit.id!,
        horses: _horses,
        serviceLine: line,
      ),
    );
    if (result != null) {
      await DatabaseService.updateServiceLine(result);
      _loadData();
    }
  }

  Future<void> _deleteServiceLine(ServiceLine line) async {
    final l10n = AppLocalizations.of(context)!;
    final confirmed = await ConfirmationDialog.show(
      context,
      title: l10n.deleteServiceLineTitle,
      message: l10n.removeQuotedItem(line.description),
    );
    if (confirmed == true) {
      await DatabaseService.deleteServiceLine(line.id!);
      _loadData();
    }
  }

  Future<void> _addCharge() async {
    final mileageRate = await DatabaseService.getMileageRate();
    if (!mounted) return;
    final result = await showDialog<VisitCharge>(
      context: context,
      builder: (_) => VisitChargeDialog(
        visitId: _visit.id!,
        defaultMileageRate: mileageRate,
      ),
    );
    if (result != null) {
      await DatabaseService.insertVisitCharge(result);
      _loadData();
    }
  }

  Future<void> _editCharge(VisitCharge charge) async {
    final mileageRate = await DatabaseService.getMileageRate();
    if (!mounted) return;
    final result = await showDialog<VisitCharge>(
      context: context,
      builder: (_) => VisitChargeDialog(
        visitId: _visit.id!,
        existingCharge: charge,
        defaultMileageRate: mileageRate,
      ),
    );
    if (result != null) {
      await DatabaseService.updateVisitCharge(result);
      _loadData();
    }
  }

  Future<void> _deleteCharge(VisitCharge charge) async {
    final l10n = AppLocalizations.of(context)!;
    final confirmed = await ConfirmationDialog.show(
      context,
      title: l10n.deleteChargeTitle,
      message: l10n.removeQuotedItem(charge.description),
    );
    if (confirmed == true) {
      await DatabaseService.deleteVisitCharge(charge.id!);
      _loadData();
    }
  }

  Future<void> _addPhoto() async {
    final l10n = AppLocalizations.of(context)!;
    final source = await showModalBottomSheet<ImageSource>(
      context: context,
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: Text(l10n.takeAPhoto),
              onTap: () => Navigator.pop(ctx, ImageSource.camera),
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: Text(l10n.chooseFromCameraRoll),
              onTap: () => Navigator.pop(ctx, ImageSource.gallery),
            ),
          ],
        ),
      ),
    );
    if (source == null) return;

    final picker = ImagePicker();
    if (source == ImageSource.gallery) {
      final images = await picker.pickMultiImage();
      if (images.isEmpty) return;
      await _addMultiplePhotos(images);
    } else {
      final image = await picker.pickImage(source: ImageSource.camera);
      if (image == null) return;
      await _addSinglePhoto(image);
    }
  }

  Future<void> _addSinglePhoto(XFile image) async {
    final l10n = AppLocalizations.of(context)!;
    final captionCtrl = TextEditingController();
    final includeOnInvoice = ValueNotifier<bool>(true);
    final selectedHorseIds = Set<int>.from(_horses.map((h) => h.id!));

    if (!mounted) return;
    final saved = await showDialog<bool>(
      context: context,
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setDialogState) => AlertDialog(
          title: Text(l10n.photoDetailsTitle),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Image.file(
                  File(image.path),
                  height: 150,
                  fit: BoxFit.cover,
                  cacheHeight: AppUtils.cachePixels(context, 150),
                ),
                const SizedBox(height: 12),
                if (_horses.isNotEmpty) ...[
                  const SizedBox(height: 8),
                  Text(l10n.tagToAnimalsLabel,
                      style: const TextStyle(fontWeight: FontWeight.w500)),
                  ..._horses.map((h) => StatefulBuilder(
                        builder: (ctx, setCheckState) => CheckboxListTile(
                          dense: true,
                          title: Text(h.name),
                          value: selectedHorseIds.contains(h.id),
                          onChanged: (checked) {
                            setCheckState(() {
                              if (checked == true) {
                                selectedHorseIds.add(h.id!);
                              } else {
                                selectedHorseIds.remove(h.id);
                              }
                            });
                          },
                        ),
                      )),
                ],
                TextField(
                  controller: captionCtrl,
                  decoration: InputDecoration(labelText: l10n.captionLabel),
                ),
                ValueListenableBuilder<bool>(
                  valueListenable: includeOnInvoice,
                  builder: (context, value, child) => SwitchListTile(
                    title: Text(l10n.includeOnInvoiceSwitch),
                    value: value,
                    onChanged: (v) => includeOnInvoice.value = v,
                  ),
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(ctx, false),
              child: Text(l10n.cancel),
            ),
            ElevatedButton(
              onPressed: () => Navigator.pop(ctx, true),
              child: Text(l10n.save),
            ),
          ],
        ),
      ),
    );

    if (saved == true) {
      final durablePath = await _copyPhotoToDocuments(image);
      if (selectedHorseIds.isEmpty) {
        await DatabaseService.insertPhoto(VisitPhoto(
          visitId: _visit.id!,
          horseId: null,
          path: durablePath,
          caption: captionCtrl.text.trim(),
          includeOnInvoice: includeOnInvoice.value,
        ));
      } else {
        for (final horseId in selectedHorseIds) {
          await DatabaseService.insertPhoto(VisitPhoto(
            visitId: _visit.id!,
            horseId: horseId,
            path: durablePath,
            caption: captionCtrl.text.trim(),
            includeOnInvoice: includeOnInvoice.value,
          ));
        }
      }
      _loadData();
    }
    captionCtrl.dispose();
  }

  Future<void> _addMultiplePhotos(List<XFile> images) async {
    final l10n = AppLocalizations.of(context)!;
    final captionCtrl = TextEditingController();
    final includeOnInvoice = ValueNotifier<bool>(true);
    final selectedHorseIds = Set<int>.from(_horses.map((h) => h.id!));

    if (!mounted) return;
    final saved = await showDialog<bool>(
      context: context,
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setDialogState) => AlertDialog(
          title: Text(l10n.addPhotosCountTitle(images.length)),
          content: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                Text(l10n.photosSelectedFromGallery(images.length)),
                const SizedBox(height: 12),
                if (_horses.isNotEmpty) ...[
                  Text(l10n.tagAllToAnimalsLabel,
                      style: const TextStyle(fontWeight: FontWeight.w500)),
                  ..._horses.map((h) => StatefulBuilder(
                        builder: (ctx, setCheckState) => CheckboxListTile(
                          dense: true,
                          title: Text(h.name),
                          value: selectedHorseIds.contains(h.id),
                          onChanged: (checked) {
                            setCheckState(() {
                              if (checked == true) {
                                selectedHorseIds.add(h.id!);
                              } else {
                                selectedHorseIds.remove(h.id);
                              }
                            });
                          },
                        ),
                      )),
                ],
                TextField(
                  controller: captionCtrl,
                  decoration:
                      InputDecoration(labelText: l10n.captionAllPhotosLabel),
                ),
                ValueListenableBuilder<bool>(
                  valueListenable: includeOnInvoice,
                  builder: (context, value, child) => SwitchListTile(
                    title: Text(l10n.includeOnInvoiceSwitch),
                    value: value,
                    onChanged: (v) => includeOnInvoice.value = v,
                  ),
                ),
              ],
            ),
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(ctx, false),
              child: Text(l10n.cancel),
            ),
            ElevatedButton(
              onPressed: () => Navigator.pop(ctx, true),
              child: Text(l10n.saveAllButton),
            ),
          ],
        ),
      ),
    );

    if (saved == true) {
      for (final image in images) {
        final durablePath = await _copyPhotoToDocuments(image);
        if (selectedHorseIds.isEmpty) {
          await DatabaseService.insertPhoto(VisitPhoto(
            visitId: _visit.id!,
            horseId: null,
            path: durablePath,
            caption: captionCtrl.text.trim(),
            includeOnInvoice: includeOnInvoice.value,
          ));
        } else {
          for (final horseId in selectedHorseIds) {
            await DatabaseService.insertPhoto(VisitPhoto(
              visitId: _visit.id!,
              horseId: horseId,
              path: durablePath,
              caption: captionCtrl.text.trim(),
              includeOnInvoice: includeOnInvoice.value,
            ));
          }
        }
      }
      _loadData();
    }
    captionCtrl.dispose();
  }

  Future<String> _copyPhotoToDocuments(XFile image) async {
    final documents = await getApplicationDocumentsDirectory();
    final photosDir = Directory(p.join(documents.path, 'photos'));
    await photosDir.create(recursive: true);

    final extension = _safePhotoExtension(image.path);
    final timestamp = DateTime.now().toUtc().microsecondsSinceEpoch;
    var candidate = File(p.join(photosDir.path, 'photo_$timestamp$extension'));
    var counter = 1;

    while (await candidate.exists()) {
      candidate = File(
        p.join(photosDir.path, 'photo_${timestamp}_$counter$extension'),
      );
      counter++;
    }

    final copied = await File(image.path).copy(candidate.path);
    return copied.path;
  }

  String _safePhotoExtension(String sourcePath) {
    final extension = p.extension(sourcePath).toLowerCase();
    if (RegExp(r'^\.[a-z0-9]{1,8}$').hasMatch(extension)) {
      return extension;
    }
    return '.jpg';
  }

  Future<void> _deletePhoto(VisitPhoto photo) async {
    final l10n = AppLocalizations.of(context)!;
    final confirmed = await ConfirmationDialog.show(
      context,
      title: l10n.deletePhotoTitle,
      message: l10n.removePhotoMessage,
    );
    if (confirmed == true) {
      await DatabaseService.deletePhoto(photo.id!);
      _loadData();
    }
  }

  Future<void> _generateInvoice() async {
    final l10n = AppLocalizations.of(context)!;
    if (_invoices.isNotEmpty) {
      // Show View / Regenerate options
      if (!mounted) return;
      await showModalBottomSheet(
        context: context,
        builder: (ctx) => SafeArea(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ListTile(
                leading: const Icon(Icons.visibility),
                title: Text(l10n.viewShareInvoiceTitle),
                onTap: () {
                  Navigator.pop(ctx);
                  _viewInvoice(_invoices.first);
                },
              ),
              ListTile(
                leading: const Icon(Icons.refresh, color: Colors.orange),
                title: Text(l10n.regenerateInvoiceTitle,
                    style: const TextStyle(color: Colors.orange)),
                subtitle: Text(l10n.regenerateInvoiceSubtitle),
                onTap: () async {
                  Navigator.pop(ctx);
                  await _confirmRegenerateInvoice();
                },
              ),
            ],
          ),
        ),
      );
      return;
    }

    final client = _client ?? await DatabaseService.getClient(_visit.clientId);
    if (client == null) return;

    try {
      final issuedAt = DateTime.now();
      final invoiceNumber =
          await DatabaseService.getNextInvoiceNumber(issuedAt);
      final file = await InvoiceService.generateInvoice(
        visit: _visit,
        client: client,
        serviceLines: _serviceLines,
        charges: _charges,
        photos: _photos,
        invoiceNumber: invoiceNumber,
      );

      final invoice = InvoiceRecord(
        visitId: _visit.id!,
        invoiceNumber: invoiceNumber,
        issuedAt: issuedAt,
        paidAt: _visit.paid ? issuedAt : null,
        total: _total,
        filePath: file.path,
        fileName: file.path.split('/').last,
      );
      final invoiceId = await DatabaseService.insertInvoice(invoice);

      if (!mounted) return;
      setState(
        () => _invoices = [
          InvoiceRecord(
            id: invoiceId,
            visitId: invoice.visitId,
            invoiceNumber: invoice.invoiceNumber,
            issuedAt: invoice.issuedAt,
            paidAt: invoice.paidAt,
            total: invoice.total,
            filePath: invoice.filePath,
            fileName: invoice.fileName,
            createdAt: invoice.createdAt,
            updatedAt: invoice.updatedAt,
          ),
        ],
      );

      final last = client.lastName.trim().replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_');
      final first = client.firstName.trim().replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_');
      final namePart = first.isNotEmpty ? '${last}_$first' : last;
      final dateStr = _visit.dateTime.toIso8601String().split('T').first;
      final shareFileName = '${namePart}_$dateStr.pdf';

      final hasInvoicePhotos = _photos.any((p) => p.includeOnInvoice);
      showModalBottomSheet(
        context: context,
        builder: (bsCtx) => SafeArea(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              if (hasInvoicePhotos) ...[
                ListTile(
                  leading: const Icon(Icons.receipt_long),
                  title: Text(l10n.shareInvoiceOnlyTitle),
                  subtitle: Text(l10n.shareInvoiceOnlySubtitle),
                  onTap: () async {
                    Navigator.pop(bsCtx);
                    try {
                      final invoiceOnlyFile =
                          await InvoiceService.generateInvoice(
                        visit: _visit,
                        client: client,
                        serviceLines: _serviceLines,
                        charges: _charges,
                        photos: _photos,
                        invoiceNumber: invoiceNumber,
                        includePhotos: false,
                      );
                      await InvoiceService.shareInvoice(
                        invoiceOnlyFile,
                        subject: l10n.invoiceSubjectFor(client.fullName),
                        fileName: shareFileName,
                      );
                    } catch (e) {
                      if (!mounted) return;
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(content: Text(l10n.errorSharingInvoiceSnackbar('$e'))),
                      );
                    }
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.photo_library),
                  title: Text(l10n.shareInvoicePhotosTitle),
                  subtitle: Text(l10n.shareInvoicePhotosSubtitle),
                  onTap: () {
                    Navigator.pop(bsCtx);
                    InvoiceService.shareInvoice(
                      file,
                      subject: l10n.invoiceSubjectFor(client.fullName),
                      fileName: shareFileName,
                    );
                  },
                ),
              ] else
                ListTile(
                  leading: const Icon(Icons.share),
                  title: Text(l10n.shareInvoicePdfTitle),
                  subtitle: Text(l10n.shareInvoicePdfSubtitle),
                  onTap: () {
                    Navigator.pop(bsCtx);
                    InvoiceService.shareInvoice(
                      file,
                      subject: l10n.invoiceSubjectFor(client.fullName),
                      fileName: shareFileName,
                    );
                  },
                ),
              ListTile(
                leading: const Icon(Icons.print),
                title: Text(l10n.printInvoiceTitle),
                onTap: () {
                  Navigator.pop(bsCtx);
                  InvoiceService.printInvoice(file);
                },
              ),
            ],
          ),
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(l10n.errorGeneratingInvoiceSnackbar('$e'))),
      );
    }
  }

  Future<void> _confirmRegenerateInvoice() async {
    if (_invoices.isEmpty) return;
    final l10n = AppLocalizations.of(context)!;
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text(l10n.regenerateInvoiceConfirmTitle),
        content: Text(l10n.regenerateInvoiceConfirmMessage),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: Text(l10n.cancel),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
                backgroundColor: Colors.orange,
                foregroundColor: Colors.white),
            onPressed: () => Navigator.pop(ctx, true),
            child: Text(l10n.regenerateButton),
          ),
        ],
      ),
    );
    if (confirmed != true) return;

    final invoice = _invoices.first;
    final f = File(invoice.filePath);
    if (await f.exists()) await f.delete();
    await DatabaseService.deleteInvoice(invoice.id!);
    setState(() => _invoices = []);
    await _generateInvoice();
  }

  Future<File?> _ensureInvoiceFile(InvoiceRecord invoice) async {
    if (invoice.filePath.isNotEmpty) {
      final existing = File(invoice.filePath);
      if (await existing.exists()) return existing;
    }

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            AppLocalizations.of(context)!.invoicePdfNotFoundSnackbar(
              invoice.fileName.isEmpty ? invoice.invoiceNumber : invoice.fileName,
            ),
          ),
        ),
      );
    }
    return null;
  }

  Future<void> _viewInvoice(InvoiceRecord invoice) async {
    final file = await _ensureInvoiceFile(invoice);
    if (!mounted || file == null) return;

    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(title: Text(invoice.invoiceNumber)),
          body: PdfPreview(
            canChangePageFormat: false,
            canChangeOrientation: false,
            canDebug: false,
            build: (_) => file.readAsBytes(),
          ),
        ),
      ),
    );
  }

  Future<void> _shareInvoiceRecord(InvoiceRecord invoice) async {
    final l10n = AppLocalizations.of(context)!;
    final file = await _ensureInvoiceFile(invoice);
    if (file == null) return;

    final hasInvoicePhotos = _photos.any((p) => p.includeOnInvoice);
    if (!hasInvoicePhotos || !mounted) {
      await InvoiceService.shareInvoice(
        file,
        subject: l10n.invoiceNumberSubject(invoice.invoiceNumber),
        fileName: invoice.fileName,
      );
      return;
    }

    final client = _client;
    showModalBottomSheet(
      context: context,
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.receipt_long),
              title: Text(l10n.shareInvoiceOnlyTitle),
              subtitle: Text(l10n.shareInvoiceOnlySubtitle),
              onTap: () async {
                Navigator.pop(ctx);
                if (client == null) return;
                try {
                  final invoiceOnlyFile =
                      await InvoiceService.generateInvoice(
                    visit: _visit,
                    client: client,
                    serviceLines: _serviceLines,
                    charges: _charges,
                    photos: _photos,
                    invoiceNumber: invoice.invoiceNumber,
                    includePhotos: false,
                  );
                  await InvoiceService.shareInvoice(
                    invoiceOnlyFile,
                    subject: l10n.invoiceNumberSubject(invoice.invoiceNumber),
                    fileName: invoice.fileName,
                  );
                } catch (e) {
                  if (!mounted) return;
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(content: Text(l10n.errorSharingInvoiceSnackbar('$e'))),
                  );
                }
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: Text(l10n.shareInvoicePhotosTitle),
              subtitle: Text(l10n.shareInvoicePhotosSubtitle),
              onTap: () {
                Navigator.pop(ctx);
                InvoiceService.shareInvoice(
                  file,
                  subject: l10n.invoiceNumberSubject(invoice.invoiceNumber),
                  fileName: invoice.fileName,
                );
              },
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _printInvoiceRecord(InvoiceRecord invoice) async {
    final file = await _ensureInvoiceFile(invoice);
    if (file == null) return;

    await InvoiceService.printInvoice(file);
  }

  Future<void> _deleteVisit() async {
    final l10n = AppLocalizations.of(context)!;
    final confirmed = await ConfirmationDialog.show(
      context,
      title: l10n.deleteVisitTitle,
      message: l10n.deleteVisitConfirmMessage,
    );
    if (confirmed == true) {
      await DatabaseService.deleteVisit(_visit.id!);
      if (mounted) Navigator.pop(context);
    }
  }

  Future<void> _editClientAddress() async {
    final client = _client;
    if (client == null) return;

    final result = await showDialog<Client>(
      context: context,
      builder: (_) => ClientFormDialog(client: client),
    );
    if (result != null) {
      await DatabaseService.updateClient(result);
      _loadData();
    }
  }

  Future<void> _openVisitAddress() async {
    final address = _client?.address.trim() ?? '';
    if (address.isEmpty) return;

    final launched = await AppUtils.openGoogleMapsSearch(address);
    if (!mounted || launched) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(AppLocalizations.of(context)!.couldNotOpenMapsSnackbar)),
    );
  }

  Future<void> _addToPhoneCalendar() async {
    final l10n = AppLocalizations.of(context)!;
    final client = _client;
    final event = Event(
      title: l10n.calendarEventTitle(client?.fullName ?? _visit.clientName),
      description: _visit.notes.trim().isEmpty
          ? l10n.calendarEventDefaultDescription
          : _visit.notes.trim(),
      location: client?.address ?? '',
      startDate: _visit.dateTime,
      endDate: _visit.dateTime.add(const Duration(hours: 1)),
    );

    try {
      final added = await Add2Calendar.addEvent2Cal(event);
      if (!mounted || added) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(l10n.calendarEventNotAddedSnackbar)),
      );
    } catch (error) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(l10n.calendarEventErrorSnackbar('$error'))),
      );
    }
  }

  Future<void> _sendReminder() async {
    final l10n = AppLocalizations.of(context)!;
    final client = _client;
    if (client == null || client.phone.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(l10n.noPhoneForClientSnackbar)),
      );
      return;
    }

    final template = await DatabaseService.getReminderTemplate();
    final message = template
        .replaceAll('{name}', client.firstName)
        .replaceAll('{date}', AppUtils.formatDate(_visit.dateTime))
        .replaceAll('{time}', AppUtils.formatTime(_visit.dateTime));

    final phone = client.phone.replaceAll(RegExp(r'[^0-9+]'), '');
    final uri = Uri.parse('sms:$phone?body=${Uri.encodeComponent(message)}');

    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
      return;
    }

    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(l10n.couldNotOpenSmsSnackbar)),
    );
  }

  void _showInsertNotesSheet() {
    final l10n = AppLocalizations.of(context)!;
    final hasClientNotes = _client?.notes.isNotEmpty == true;
    final horsesWithNotes =
        _horses.where((h) => h.notes.isNotEmpty).toList();

    if (!hasClientNotes && horsesWithNotes.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(l10n.noSavedNotesSnackbar)),
      );
      return;
    }

    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (ctx) => DraggableScrollableSheet(
        initialChildSize: 0.5,
        minChildSize: 0.3,
        maxChildSize: 0.85,
        expand: false,
        builder: (ctx, scrollCtrl) => Column(
          children: [
            Padding(
              padding: const EdgeInsets.all(16),
              child: Text(l10n.insertFromNotesTitle,
                  style: const TextStyle(
                      fontWeight: FontWeight.bold, fontSize: 16)),
            ),
            const Divider(height: 1),
            Expanded(
              child: ListView(
                controller: scrollCtrl,
                padding: const EdgeInsets.symmetric(horizontal: 16),
                children: [
                  if (hasClientNotes) ...[
                    const SizedBox(height: 12),
                    Text(
                      l10n.clientNotesHeader(_client!.fullName),
                      style: const TextStyle(fontWeight: FontWeight.w600),
                    ),
                    const SizedBox(height: 4),
                    Text(_client!.notes),
                    TextButton.icon(
                      icon: const Icon(Icons.add, size: 18),
                      label: Text(l10n.insertButton),
                      onPressed: () {
                        final current = _invoiceNotesCtrl.text;
                        _invoiceNotesCtrl.text = current.isEmpty
                            ? _client!.notes
                            : '$current\n\n${_client!.notes}';
                        _invoiceNotesCtrl.selection =
                            TextSelection.fromPosition(TextPosition(
                                offset: _invoiceNotesCtrl.text.length));
                      },
                    ),
                  ],
                  for (final horse in horsesWithNotes) ...[
                    const SizedBox(height: 12),
                    Text(
                      l10n.animalNotesHeader(horse.name),
                      style: const TextStyle(fontWeight: FontWeight.w600),
                    ),
                    const SizedBox(height: 4),
                    Text(horse.notes),
                    TextButton.icon(
                      icon: const Icon(Icons.add, size: 18),
                      label: Text(l10n.insertButton),
                      onPressed: () {
                        final current = _invoiceNotesCtrl.text;
                        _invoiceNotesCtrl.text = current.isEmpty
                            ? horse.notes
                            : '$current\n\n${horse.notes}';
                        _invoiceNotesCtrl.selection =
                            TextSelection.fromPosition(TextPosition(
                                offset: _invoiceNotesCtrl.text.length));
                      },
                    ),
                  ],
                  const SizedBox(height: 16),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAddressCard(AppLocalizations l10n) {
    final address = _client?.address.trim() ?? '';

    if (address.isEmpty) {
      return Card(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(
                    Icons.location_off_outlined,
                    color: Theme.of(context).colorScheme.outline,
                  ),
                  const SizedBox(width: 12),
                  Text(
                    l10n.noAddressSaved,
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                ],
              ),
              const SizedBox(height: 12),
              OutlinedButton.icon(
                onPressed: _editClientAddress,
                icon: const Icon(Icons.edit_location_alt),
                label: Text(l10n.editClientTitle),
              ),
            ],
          ),
        ),
      );
    }

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.location_on_outlined),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        l10n.appointmentAddressTitle,
                        style: Theme.of(context).textTheme.titleMedium,
                      ),
                      const SizedBox(height: 4),
                      Text(address),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            FilledButton.icon(
              onPressed: _openVisitAddress,
              icon: const Icon(Icons.directions),
              label: Text(l10n.openInGoogleMaps),
            ),
          ],
        ),
      ),
    );
  }

  void _showPhotoFullScreen(VisitPhoto photo) {
    final l10n = AppLocalizations.of(context)!;
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(
            title: Text(photo.caption.isNotEmpty ? photo.caption : l10n.photoDefaultTitle),
          ),
          body: Center(
            child: InteractiveViewer(
              child: Image.file(
                File(photo.path),
                cacheWidth: AppUtils.cachePixels(
                  context,
                  MediaQuery.of(context).size.width,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    if (_loading) {
      return Scaffold(
        appBar: AppBar(title: Text(l10n.visitTitle)),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    final hasLines = _serviceLines.isNotEmpty || _charges.isNotEmpty;

    return Scaffold(
      appBar: AppBar(
        title: Text(_visit.clientName),
        actions: [
          if (hasLines)
            IconButton(
              icon: const Icon(Icons.receipt_long),
              tooltip: _invoices.isEmpty ? l10n.generateInvoiceTooltip : l10n.regenerateInvoiceTooltip,
              onPressed: _generateInvoice,
            ),
          PopupMenuButton<String>(
            onSelected: (value) {
              if (value == 'edit') {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => NewVisitScreen(visit: _visit),
                  ),
                ).then((_) => _loadData());
              }
              if (value == 'delete') _deleteVisit();
            },
            itemBuilder: (context) => [
              PopupMenuItem(
                value: 'edit',
                child: Text(l10n.editVisitMenuItem),
              ),
              PopupMenuItem(
                value: 'delete',
                child: Text(l10n.deleteVisitMenuItem, style: const TextStyle(color: Colors.red)),
              ),
            ],
          ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: _loadData,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Expanded(
                          child: Text(
                            AppUtils.formatDateTimeForInvoice(_visit.dateTime),
                            style: Theme.of(context).textTheme.titleLarge,
                          ),
                        ),
                        VisitStatusChip(visit: _visit),
                      ],
                    ),
                    if (_visit.notes.isNotEmpty) ...[
                      const SizedBox(height: 8),
                      Text(
                        l10n.invoiceNotesPrefix(_visit.notes),
                        style: Theme.of(context).textTheme.bodySmall?.copyWith(
                              fontStyle: FontStyle.italic,
                            ),
                      ),
                    ],
                    const SizedBox(height: 12),
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children: [
                        OutlinedButton.icon(
                          onPressed: _addToPhoneCalendar,
                          icon: const Icon(Icons.event),
                          label: Text(l10n.addToPhoneCalendarButton),
                        ),
                        OutlinedButton.icon(
                          onPressed: _sendReminder,
                          icon: const Icon(Icons.sms_outlined),
                          label: Text(l10n.sendReminderButton),
                        ),
                      ],
                    ),
                    if (_visit.isAutoGenerated) ...[
                      const SizedBox(height: 12),
                      FilledButton.icon(
                        onPressed: _confirmProjectedVisit,
                        icon: const Icon(Icons.event_available),
                        label: Text(l10n.confirmAppointmentButton),
                      ),
                    ],
                    const SizedBox(height: 12),
                    SwitchListTile(
                      title: Text(l10n.visitCompletedSwitch),
                      value: _visit.completed,
                      onChanged: _toggleCompleted,
                      contentPadding: EdgeInsets.zero,
                    ),
                    SwitchListTile(
                      title: Text(l10n.paymentReceivedSwitch),
                      value: _visit.paid,
                      onChanged: _togglePaid,
                      contentPadding: EdgeInsets.zero,
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
            _buildAddressCard(l10n),
            const SizedBox(height: 16),
            SectionHeader(title: l10n.animalsCountTitle(_horses.length)),
            if (_horses.isEmpty)
              Padding(
                padding: const EdgeInsets.all(16),
                child: Text(l10n.noAnimalsForVisit),
              )
            else
              ..._horses.map((h) => ListTile(
                    leading: HorseAvatar(horse: h, radius: 20),
                    title: Text(h.name),
                  )),
            const SizedBox(height: 16),
            SectionHeader(
              title: l10n.billingTitle,
              onAdd: _addServiceLine,
              addLabel: l10n.addServiceLineLabel,
            ),
            if (_serviceLines.isEmpty)
              Padding(
                padding: const EdgeInsets.all(16),
                child: Text(l10n.noServiceLinesYet),
              )
            else
              ..._serviceLines.map((line) => ServiceLineCard(
                    line: line,
                    onEdit: () => _editServiceLine(line),
                    onDelete: () => _deleteServiceLine(line),
                  )),
            const SizedBox(height: 16),
            SectionHeader(
              title: l10n.travelIncidentalsTitle,
              onAdd: _addCharge,
              addLabel: l10n.addChargeLabel,
            ),
            if (_charges.isEmpty)
              Padding(
                padding: const EdgeInsets.all(16),
                child: Text(l10n.noChargesYet),
              )
            else
              ..._charges.map((charge) => Card(
                    margin:
                        const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                    child: ListTile(
                      leading: CircleAvatar(
                        backgroundColor:
                            Theme.of(context).colorScheme.secondaryContainer,
                        child: Icon(
                          charge.type.icon,
                          color: Theme.of(context)
                              .colorScheme
                              .onSecondaryContainer,
                        ),
                      ),
                      title: Text(charge.description),
                      subtitle: charge.type.isMileageBased
                          ? Text(
                              '${AppUtils.formatDistance(charge.quantity)} @ ${AppUtils.formatCurrency(charge.rate)}/${AppUtils.distanceUnit}')
                          : null,
                      trailing: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(
                            AppUtils.formatCurrency(charge.total),
                            style:
                                Theme.of(context).textTheme.titleMedium,
                          ),
                          PopupMenuButton<String>(
                            onSelected: (value) {
                              if (value == 'edit') _editCharge(charge);
                              if (value == 'delete') _deleteCharge(charge);
                            },
                            itemBuilder: (context) => [
                              PopupMenuItem(
                                  value: 'edit', child: Text(l10n.edit)),
                              PopupMenuItem(
                                value: 'delete',
                                child: Text(l10n.delete,
                                    style: const TextStyle(color: Colors.red)),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  )),
            if (hasLines) ...[
              const Divider(height: 24),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    if (_charges.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 4),
                        child: Text(
                          l10n.servicesAndTravelSummary(
                            AppUtils.formatCurrency(_serviceLinesTotal),
                            AppUtils.formatCurrency(_chargesTotal),
                          ),
                          style: Theme.of(context).textTheme.bodySmall,
                        ),
                      ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(l10n.totalLabelPlain,
                            style: Theme.of(context)
                                .textTheme
                                .titleLarge
                                ?.copyWith(fontWeight: FontWeight.bold)),
                        Text(
                          AppUtils.formatCurrency(_total),
                          style: Theme.of(context)
                              .textTheme
                              .titleLarge
                              ?.copyWith(
                                fontWeight: FontWeight.bold,
                                color: _visit.paid
                                    ? Colors.green
                                    : Theme.of(context).colorScheme.primary,
                              ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
            const SizedBox(height: 16),
            // Invoice Notes section
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              child: TextField(
                controller: _invoiceNotesCtrl,
                decoration: InputDecoration(
                  labelText: l10n.invoiceNotesLabel,
                  hintText: l10n.invoiceNotesHint,
                  border: const OutlineInputBorder(),
                  suffixIcon: IconButton(
                    icon: const Icon(Icons.note_add),
                    tooltip: l10n.insertFromSavedNotesTooltip,
                    onPressed: _showInsertNotesSheet,
                  ),
                ),
                maxLines: 4,
                onChanged: (_) => _scheduleNotesSave(),
              ),
            ),
            const SizedBox(height: 16),
            if (hasLines)
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: ElevatedButton.icon(
                  onPressed: _generateInvoice,
                  icon: const Icon(Icons.receipt_long),
                  label: Text(_invoices.isEmpty
                      ? l10n.generateInvoiceButton
                      : l10n.regenerateInvoiceTitle),
                  style: ElevatedButton.styleFrom(
                    minimumSize: const Size(double.infinity, 48),
                  ),
                ),
              ),
            const SizedBox(height: 16),
            SectionHeader(
              title: l10n.invoiceHistoryTitle,
              onAdd: hasLines && _invoices.isEmpty ? _generateInvoice : null,
              addLabel: l10n.createInvoiceButton,
            ),
            if (_invoices.isEmpty)
              Padding(
                padding: const EdgeInsets.all(16),
                child: !hasLines
                    ? Text(l10n.addServiceLinesBeforeInvoice)
                    : ElevatedButton.icon(
                        onPressed: _generateInvoice,
                        icon: const Icon(Icons.receipt_long),
                        label: Text(l10n.createInvoiceButton),
                        style: ElevatedButton.styleFrom(
                          minimumSize: const Size(double.infinity, 48),
                        ),
                      ),
              )
            else
              ..._invoices.map(
                (invoice) => Card(
                  margin: const EdgeInsets.symmetric(
                    horizontal: 16,
                    vertical: 4,
                  ),
                  child: ListTile(
                    leading: CircleAvatar(
                      backgroundColor: invoice.paidAt != null
                          ? Colors.green.shade100
                          : Theme.of(context).colorScheme.secondaryContainer,
                      child: Icon(
                        invoice.paidAt != null
                            ? Icons.check_circle
                            : Icons.receipt_long,
                        color: invoice.paidAt != null
                            ? Colors.green
                            : Theme.of(context)
                                .colorScheme
                                .onSecondaryContainer,
                      ),
                    ),
                    title: Text(invoice.invoiceNumber),
                    subtitle: Text(
                      '${AppUtils.formatDate(invoice.issuedAt)} · ${invoice.paidAt != null ? l10n.paidInFull : l10n.unpaidLabel}',
                      style: TextStyle(
                        color: invoice.paidAt != null
                            ? Colors.green
                            : null,
                        fontWeight: invoice.paidAt != null
                            ? FontWeight.w600
                            : null,
                      ),
                    ),
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text(AppUtils.formatCurrency(invoice.total)),
                        PopupMenuButton<String>(
                          onSelected: (value) {
                            if (value == 'view') _viewInvoice(invoice);
                            if (value == 'share') _shareInvoiceRecord(invoice);
                            if (value == 'print') _printInvoiceRecord(invoice);
                          },
                          itemBuilder: (context) => [
                            PopupMenuItem(value: 'view', child: Text(l10n.view)),
                            PopupMenuItem(value: 'share', child: Text(l10n.share)),
                            PopupMenuItem(value: 'print', child: Text(l10n.print)),
                          ],
                        ),
                      ],
                    ),
                    onTap: () => _viewInvoice(invoice),
                  ),
                ),
              ),
            const SizedBox(height: 16),
            SectionHeader(
              title: l10n.photosCountTitle(_photos.length),
              onAdd: _addPhoto,
              addLabel: l10n.addPhotoLabel,
            ),
            if (_photos.isEmpty)
              Padding(
                padding: const EdgeInsets.all(16),
                child: Text(l10n.noPhotosYet),
              )
            else
              PhotoGrid(
                photos: _photos,
                onTap: (photo) => _showPhotoFullScreen(photo),
                onLongPress: (photo) => _deletePhoto(photo),
              ),
          ],
        ),
      ),
    );
  }
}
