import 'dart:io';
import 'package:add_2_calendar/add_2_calendar.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';
import '../models/models.dart';
import '../services/database_service.dart';
import '../services/invoice_service.dart';
import '../utils/utils.dart';
import '../widgets/widgets.dart';
import 'screens.dart';

class VisitDetailScreen extends StatefulWidget {
  final Visit visit;
  const VisitDetailScreen({super.key, required this.visit});

  @override
  State<VisitDetailScreen> createState() => _VisitDetailScreenState();
}

class _VisitDetailScreenState extends State<VisitDetailScreen> {
  late Visit _visit;
  Client? _client;
  List<Horse> _horses = [];
  List<ServiceLine> _serviceLines = [];
  List<VisitCharge> _charges = [];
  List<VisitPhoto> _photos = [];
  List<InvoiceRecord> _invoices = [];
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _visit = widget.visit;
    _loadData();
  }

  Future<void> _loadData() async {
    final visit = await DatabaseService.getVisit(_visit.id!);
    final horses = await DatabaseService.getHorsesForVisit(_visit.id!);
    final serviceLines = await DatabaseService.getServiceLines(_visit.id!);
    final charges = await DatabaseService.getVisitCharges(_visit.id!);
    final photos = await DatabaseService.getPhotos(_visit.id!);
    final invoices = await DatabaseService.getInvoicesForVisit(_visit.id!);
    final client = await DatabaseService.getClient(_visit.clientId);
    if (mounted) {
      setState(() {
        if (visit != null) _visit = visit;
        _client = client;
        _horses = horses;
        _serviceLines = serviceLines;
        _charges = charges;
        _photos = photos;
        _invoices = invoices;
        _loading = false;
      });
    }
  }

  double get _serviceLinesTotal =>
      _serviceLines.fold(0.0, (sum, line) => sum + line.lineTotal);
  double get _chargesTotal =>
      _charges.fold(0.0, (sum, c) => sum + c.total);
  double get _total => _serviceLinesTotal + _chargesTotal;

  Future<void> _togglePaid(bool value) async {
    final wasPaid = _visit.paid;
    await DatabaseService.setVisitPaid(_visit.id!, value);
    await DatabaseService.setInvoicesPaidForVisit(_visit.id!, value);
    setState(() {
      _visit = Visit(
        id: _visit.id,
        clientId: _visit.clientId,
        clientName: _visit.clientName,
        dateTime: _visit.dateTime,
        notes: _visit.notes,
        paid: value,
        completed: _visit.completed,
        recurrenceWeeks: _visit.recurrenceWeeks,
        nextRecurringVisitId: _visit.nextRecurringVisitId,
        isAutoGenerated: _visit.isAutoGenerated,
        createdAt: _visit.createdAt,
      );
    });
    if (!mounted) return;
    if (!wasPaid &&
        value &&
        _visit.recurrenceWeeks != null &&
        _visit.nextRecurringVisitId == null) {
      final scheduleNext = await ConfirmationDialog.show(
        context,
        title: 'Recurring Visit',
        message: 'Schedule next recurring visit?',
      );
      if (scheduleNext == true) {
        await DatabaseService.generateRecurringChain(_visit, weeksAhead: 10);
      }
    }
    _loadData();
  }

  Future<void> _toggleCompleted(bool value) async {
    await DatabaseService.setVisitCompleted(_visit.id!, value);
    setState(() {
      _visit = Visit(
        id: _visit.id,
        clientId: _visit.clientId,
        clientName: _visit.clientName,
        dateTime: _visit.dateTime,
        notes: _visit.notes,
        paid: _visit.paid,
        completed: value,
        recurrenceWeeks: _visit.recurrenceWeeks,
        nextRecurringVisitId: _visit.nextRecurringVisitId,
        isAutoGenerated: _visit.isAutoGenerated,
        createdAt: _visit.createdAt,
      );
    });
  }

  Future<void> _confirmProjectedVisit() async {
    await DatabaseService.confirmAutoGeneratedVisit(_visit.id!);
    await _loadData();
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Appointment confirmed')),
    );
  }

  Future<void> _addServiceLine() async {
    final result = await showDialog<ServiceLine>(
      context: context,
      builder: (_) => ServiceLineDialog(
        visitId: _visit.id!,
        horses: _horses,
      ),
    );
    if (result != null) {
      await DatabaseService.insertServiceLine(result);
      _loadData();
    }
  }

  Future<void> _editServiceLine(ServiceLine line) async {
    final result = await showDialog<ServiceLine>(
      context: context,
      builder: (_) => ServiceLineDialog(
        visitId: _visit.id!,
        horses: _horses,
        serviceLine: line,
      ),
    );
    if (result != null) {
      await DatabaseService.updateServiceLine(result);
      _loadData();
    }
  }

  Future<void> _deleteServiceLine(ServiceLine line) async {
    final confirmed = await ConfirmationDialog.show(
      context,
      title: 'Delete Service Line',
      message: 'Remove "${line.description}"?',
    );
    if (confirmed == true) {
      await DatabaseService.deleteServiceLine(line.id!);
      _loadData();
    }
  }

  Future<void> _addCharge() async {
    final mileageRate = await DatabaseService.getMileageRate();
    final result = await showDialog<VisitCharge>(
      context: context,
      builder: (_) => VisitChargeDialog(
        visitId: _visit.id!,
        defaultMileageRate: mileageRate,
      ),
    );
    if (result != null) {
      await DatabaseService.insertVisitCharge(result);
      _loadData();
    }
  }

  Future<void> _editCharge(VisitCharge charge) async {
    final mileageRate = await DatabaseService.getMileageRate();
    final result = await showDialog<VisitCharge>(
      context: context,
      builder: (_) => VisitChargeDialog(
        visitId: _visit.id!,
        existingCharge: charge,
        defaultMileageRate: mileageRate,
      ),
    );
    if (result != null) {
      await DatabaseService.updateVisitCharge(result);
      _loadData();
    }
  }

  Future<void> _deleteCharge(VisitCharge charge) async {
    final confirmed = await ConfirmationDialog.show(
      context,
      title: 'Delete Charge',
      message: 'Remove "${charge.description}"?',
    );
    if (confirmed == true) {
      await DatabaseService.deleteVisitCharge(charge.id!);
      _loadData();
    }
  }

  Future<void> _addPhoto() async {
    // Let the user choose between camera and gallery (camera roll).
    final source = await showModalBottomSheet<ImageSource>(
      context: context,
      builder: (ctx) => SafeArea(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: const Text('Take a photo'),
              onTap: () => Navigator.pop(ctx, ImageSource.camera),
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: const Text('Choose from camera roll'),
              onTap: () => Navigator.pop(ctx, ImageSource.gallery),
            ),
          ],
        ),
      ),
    );
    if (source == null) return;

    final picker = ImagePicker();
    final image = await picker.pickImage(source: source);
    if (image == null) return;

    final captionCtrl = TextEditingController();
    final includeOnInvoice = ValueNotifier<bool>(true);
    final selectedHorseIds = Set<int>.from(_horses.map((h) => h.id!));

    if (mounted) {
      final saved = await showDialog<bool>(
        context: context,
        builder: (ctx) => StatefulBuilder(
          builder: (ctx, setDialogState) => AlertDialog(
            title: const Text('Photo Details'),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Image.file(File(image.path), height: 150, fit: BoxFit.cover),
                  const SizedBox(height: 12),
                  if (_horses.isNotEmpty) ...[
                    const SizedBox(height: 8),
                    const Text('Tag to animal(s):',
                        style: TextStyle(fontWeight: FontWeight.w500)),
                    ..._horses.map((h) => StatefulBuilder(
                          builder: (ctx, setCheckState) => CheckboxListTile(
                            dense: true,
                            title: Text(h.name),
                            value: selectedHorseIds.contains(h.id),
                            onChanged: (checked) {
                              setCheckState(() {
                                if (checked == true) {
                                  selectedHorseIds.add(h.id!);
                                } else {
                                  selectedHorseIds.remove(h.id);
                                }
                              });
                            },
                          ),
                        )),
                  ],
                  TextField(
                    controller: captionCtrl,
                    decoration: const InputDecoration(labelText: 'Caption'),
                  ),
                  ValueListenableBuilder<bool>(
                    valueListenable: includeOnInvoice,
                    builder: (context, value, child) => SwitchListTile(
                      title: const Text('Include on invoice'),
                      value: value,
                      onChanged: (v) => includeOnInvoice.value = v,
                    ),
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx, false),
                child: const Text('Cancel'),
              ),
              ElevatedButton(
                onPressed: () => Navigator.pop(ctx, true),
                child: const Text('Save'),
              ),
            ],
          ),
        ),
      );

      if (saved == true) {
        final durablePath = await _copyPhotoToDocuments(image);

        if (selectedHorseIds.isEmpty) {
          await DatabaseService.insertPhoto(VisitPhoto(
            visitId: _visit.id!,
            horseId: null,
            path: durablePath,
            caption: captionCtrl.text.trim(),
            includeOnInvoice: includeOnInvoice.value,
          ));
        } else {
          for (final horseId in selectedHorseIds) {
            await DatabaseService.insertPhoto(VisitPhoto(
              visitId: _visit.id!,
              horseId: horseId,
              path: durablePath,
              caption: captionCtrl.text.trim(),
              includeOnInvoice: includeOnInvoice.value,
            ));
          }
        }
        _loadData();
      }
      captionCtrl.dispose();
    }
  }

  Future<String> _copyPhotoToDocuments(XFile image) async {
    final documents = await getApplicationDocumentsDirectory();
    final photosDir = Directory(p.join(documents.path, 'photos'));
    await photosDir.create(recursive: true);

    final extension = _safePhotoExtension(image.path);
    final timestamp = DateTime.now().toUtc().microsecondsSinceEpoch;
    var candidate = File(p.join(photosDir.path, 'photo_$timestamp$extension'));
    var counter = 1;

    while (await candidate.exists()) {
      candidate = File(
        p.join(photosDir.path, 'photo_${timestamp}_$counter$extension'),
      );
      counter++;
    }

    final copied = await File(image.path).copy(candidate.path);
    return copied.path;
  }

  String _safePhotoExtension(String sourcePath) {
    final extension = p.extension(sourcePath).toLowerCase();
    if (RegExp(r'^\.[a-z0-9]{1,8}$').hasMatch(extension)) {
      return extension;
    }
    return '.jpg';
  }

  Future<void> _deletePhoto(VisitPhoto photo) async {
    final confirmed = await ConfirmationDialog.show(
      context,
      title: 'Delete Photo',
      message: 'Remove this photo?',
    );
    if (confirmed == true) {
      await DatabaseService.deletePhoto(photo.id!);
      _loadData();
    }
  }

  Future<void> _generateInvoice() async {
    if (_invoices.isNotEmpty) {
      await _viewInvoice(_invoices.first);
      return;
    }

    final client = await DatabaseService.getClient(_visit.clientId);
    if (client == null) return;

    try {
      final issuedAt = DateTime.now();
      final invoiceNumber =
          await DatabaseService.getNextInvoiceNumber(issuedAt);
      final file = await InvoiceService.generateInvoice(
        visit: _visit,
        client: client,
        serviceLines: _serviceLines,
        charges: _charges,
        photos: _photos,
        invoiceNumber: invoiceNumber,
      );

      final invoice = InvoiceRecord(
        visitId: _visit.id!,
        invoiceNumber: invoiceNumber,
        issuedAt: issuedAt,
        paidAt: _visit.paid ? issuedAt : null,
        total: _total,
        filePath: file.path,
        fileName: file.path.split('/').last,
      );
      final invoiceId = await DatabaseService.insertInvoice(invoice);

      if (!mounted) return;
      setState(
        () => _invoices = [
          InvoiceRecord(
            id: invoiceId,
            visitId: invoice.visitId,
            invoiceNumber: invoice.invoiceNumber,
            issuedAt: invoice.issuedAt,
            paidAt: invoice.paidAt,
            total: invoice.total,
            filePath: invoice.filePath,
            fileName: invoice.fileName,
            createdAt: invoice.createdAt,
            updatedAt: invoice.updatedAt,
          ),
        ],
      );

      showModalBottomSheet(
        context: context,
        builder: (_) => SafeArea(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ListTile(
                leading: const Icon(Icons.share),
                title: const Text('Share Invoice (PDF)'),
                subtitle:
                    const Text('Send via any app - Gmail, WhatsApp, etc.'),
                onTap: () {
                  Navigator.pop(context);

                  final safeClientName = client.fullName
                      .replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '_')
                      .replaceAll(RegExp(r'_+'), '_')
                      .replaceAll(RegExp(r'^_|_$'), '');

                  final date =
                      _visit.dateTime.toIso8601String().split('T').first;
                  final docType = _visit.paid ? 'Receipt' : 'Invoice';
                  final fileName = '${safeClientName}_${date}_$docType.pdf';

                  InvoiceService.shareInvoice(
                    file,
                    subject: '$docType for ${client.fullName}',
                    fileName: fileName,
                  );
                },
              ),
              ListTile(
                leading: const Icon(Icons.print),
                title: const Text('Print Invoice'),
                onTap: () {
                  Navigator.pop(context);
                  InvoiceService.printInvoice(file);
                },
              ),
            ],
          ),
        ),
      );
    } catch (e) {
      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Error generating invoice: $e')),
      );
    }
  }

  Future<File?> _ensureInvoiceFile(InvoiceRecord invoice) async {
    if (invoice.filePath.isNotEmpty) {
      final existing = File(invoice.filePath);
      if (await existing.exists()) return existing;
    }

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            'Invoice PDF not found: ${invoice.fileName.isEmpty ? invoice.invoiceNumber : invoice.fileName}',
          ),
        ),
      );
    }
    return null;
  }

  Future<void> _viewInvoice(InvoiceRecord invoice) async {
    final file = await _ensureInvoiceFile(invoice);
    if (!mounted || file == null) return;

    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(title: Text(invoice.invoiceNumber)),
          body: PdfPreview(
            canChangePageFormat: false,
            canChangeOrientation: false,
            canDebug: false,
            build: (_) => file.readAsBytes(),
          ),
        ),
      ),
    );
  }

  Future<void> _shareInvoiceRecord(InvoiceRecord invoice) async {
    final file = await _ensureInvoiceFile(invoice);
    if (file == null) return;

    await InvoiceService.shareInvoice(
      file,
      subject: 'Invoice ${invoice.invoiceNumber}',
      fileName: invoice.fileName,
    );
  }

  Future<void> _printInvoiceRecord(InvoiceRecord invoice) async {
    final file = await _ensureInvoiceFile(invoice);
    if (file == null) return;

    await InvoiceService.printInvoice(file);
  }

  Future<void> _deleteVisit() async {
    final confirmed = await ConfirmationDialog.show(
      context,
      title: 'Delete Visit',
      message: 'Are you sure you want to delete this visit?',
    );
    if (confirmed == true) {
      await DatabaseService.deleteVisit(_visit.id!);
      if (mounted) Navigator.pop(context);
    }
  }

  Future<void> _editClientAddress() async {
    final client = _client;
    if (client == null) return;

    final result = await showDialog<Client>(
      context: context,
      builder: (_) => ClientFormDialog(client: client),
    );
    if (result != null) {
      await DatabaseService.updateClient(result);
      _loadData();
    }
  }

  Future<void> _openVisitAddress() async {
    final address = _client?.address.trim() ?? '';
    if (address.isEmpty) return;

    final launched = await AppUtils.openGoogleMapsSearch(address);
    if (!mounted || launched) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Could not open Google Maps')),
    );
  }

  Future<void> _addToPhoneCalendar() async {
    final client = _client;
    final event = Event(
      title: 'Farrier - ${client?.fullName ?? _visit.clientName}',
      description:
          _visit.notes.trim().isEmpty ? 'Farrier visit' : _visit.notes.trim(),
      location: client?.address ?? '',
      startDate: _visit.dateTime,
      endDate: _visit.dateTime.add(const Duration(hours: 1)),
    );

    try {
      final added = await Add2Calendar.addEvent2Cal(event);
      if (!mounted || added) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Calendar event could not be added.')),
      );
    } catch (error) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Calendar event could not be added: $error')),
      );
    }
  }

  Future<void> _sendReminder() async {
    final phone = _client?.phone.trim() ?? '';
    if (phone.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
            content: Text('No phone number is saved for this client.')),
      );
      return;
    }

    final message = 'Hi, this is a reminder for your farrier appointment on '
        '${AppUtils.formatDate(_visit.dateTime)} at '
        '${AppUtils.formatTime(_visit.dateTime)}.';
    final uri = Uri(
      scheme: 'sms',
      path: phone,
      queryParameters: {'body': message},
    );

    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
      return;
    }

    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Could not open the SMS app.')),
    );
  }

  Widget _buildAddressCard() {
    final address = _client?.address.trim() ?? '';

    if (address.isEmpty) {
      return Card(
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(
                    Icons.location_off_outlined,
                    color: Theme.of(context).colorScheme.outline,
                  ),
                  const SizedBox(width: 12),
                  Text(
                    'No address saved',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                ],
              ),
              const SizedBox(height: 12),
              OutlinedButton.icon(
                onPressed: _editClientAddress,
                icon: const Icon(Icons.edit_location_alt),
                label: const Text('Edit Client'),
              ),
            ],
          ),
        ),
      );
    }

    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.location_on_outlined),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Appointment Address',
                        style: Theme.of(context).textTheme.titleMedium,
                      ),
                      const SizedBox(height: 4),
                      Text(address),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            FilledButton.icon(
              onPressed: _openVisitAddress,
              icon: const Icon(Icons.directions),
              label: const Text('Open in Google Maps'),
            ),
          ],
        ),
      ),
    );
  }

  void _showPhotoFullScreen(VisitPhoto photo) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => Scaffold(
          appBar: AppBar(
            title: Text(photo.caption.isNotEmpty ? photo.caption : 'Photo'),
          ),
          body: Center(
            child: InteractiveViewer(
              child: Image.file(File(photo.path)),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    if (_loading) {
      return Scaffold(
        appBar: AppBar(title: const Text('Visit')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    return Scaffold(
      appBar: AppBar(
        title: Text(_visit.clientName),
        actions: [
          if (_serviceLines.isNotEmpty || _charges.isNotEmpty)
            IconButton(
              icon: const Icon(Icons.receipt_long),
              tooltip: _invoices.isEmpty ? 'Create Invoice' : 'View Invoice',
              onPressed: _invoices.isEmpty
                  ? _generateInvoice
                  : () => _viewInvoice(_invoices.first),
            ),
          PopupMenuButton<String>(
            onSelected: (value) {
              if (value == 'edit') {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => NewVisitScreen(visit: _visit),
                  ),
                ).then((_) => _loadData());
              }
              if (value == 'delete') _deleteVisit();
            },
            itemBuilder: (context) => [
              const PopupMenuItem(
                value: 'edit',
                child: Text('Edit Visit'),
              ),
              const PopupMenuItem(
                value: 'delete',
                child:
                    Text('Delete Visit', style: TextStyle(color: Colors.red)),
              ),
            ],
          ),
        ],
      ),
      body: RefreshIndicator(
        onRefresh: _loadData,
        child: ListView(
          padding: const EdgeInsets.all(16),
          children: [
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Expanded(
                          child: Text(
                            AppUtils.formatDateTimeForInvoice(_visit.dateTime),
                            style: Theme.of(context).textTheme.titleLarge,
                          ),
                        ),
                        VisitStatusChip(visit: _visit),
                      ],
                    ),
                    if (_visit.notes.isNotEmpty) ...[
                      const SizedBox(height: 8),
                      Text(_visit.notes),
                    ],
                    const SizedBox(height: 12),
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children: [
                        OutlinedButton.icon(
                          onPressed: _addToPhoneCalendar,
                          icon: const Icon(Icons.event),
                          label: const Text('Add to Phone Calendar'),
                        ),
                        OutlinedButton.icon(
                          onPressed: _sendReminder,
                          icon: const Icon(Icons.sms_outlined),
                          label: const Text('Send Reminder'),
                        ),
                      ],
                    ),
                    if (_visit.isAutoGenerated) ...[
                      const SizedBox(height: 12),
                      FilledButton.icon(
                        onPressed: _confirmProjectedVisit,
                        icon: const Icon(Icons.event_available),
                        label: const Text('Confirm this appointment'),
                      ),
                    ],
                    const SizedBox(height: 12),
                    SwitchListTile(
                      title: const Text('Visit completed'),
                      value: _visit.completed,
                      onChanged: _toggleCompleted,
                      contentPadding: EdgeInsets.zero,
                    ),
                    SwitchListTile(
                      title: const Text('Payment received'),
                      value: _visit.paid,
                      onChanged: _togglePaid,
                      contentPadding: EdgeInsets.zero,
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
            _buildAddressCard(),
            const SizedBox(height: 16),
            SectionHeader(title: 'Animals (${_horses.length})'),
            if (_horses.isEmpty)
              const Padding(
                padding: EdgeInsets.all(16),
                child: Text('No animals selected for this visit'),
              )
            else
              ..._horses.map((h) => ListTile(
                    leading: HorseAvatar(horse: h, radius: 20),
                    title: Text(h.name),
                  )),
            const SizedBox(height: 16),
            SectionHeader(
              title: 'Billing',
              onAdd: _addServiceLine,
              addLabel: 'Add Service Line',
            ),
            if (_serviceLines.isEmpty)
              const Padding(
                padding: EdgeInsets.all(16),
                child: Text('No service lines yet'),
              )
            else
              ..._serviceLines.map((line) => ServiceLineCard(
                    line: line,
                    onEdit: () => _editServiceLine(line),
                    onDelete: () => _deleteServiceLine(line),
                  )),
            const SizedBox(height: 16),
            SectionHeader(
              title: 'Travel & Incidentals',
              onAdd: _addCharge,
              addLabel: 'Add Charge',
            ),
            if (_charges.isEmpty)
              const Padding(
                padding: EdgeInsets.all(16),
                child: Text('No travel or incidental charges yet'),
              )
            else
              ..._charges.map((charge) => Card(
                    margin:
                        const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                    child: ListTile(
                      leading: CircleAvatar(
                        backgroundColor:
                            Theme.of(context).colorScheme.secondaryContainer,
                        child: Icon(
                          charge.type.icon,
                          color:
                              Theme.of(context).colorScheme.onSecondaryContainer,
                        ),
                      ),
                      title: Text(charge.description),
                      subtitle: charge.type.isMileageBased
                          ? Text(
                              '${charge.quantity} mi @ ${AppUtils.formatCurrency(charge.rate)}/mi')
                          : null,
                      trailing: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(
                            AppUtils.formatCurrency(charge.total),
                            style: Theme.of(context).textTheme.titleMedium,
                          ),
                          PopupMenuButton<String>(
                            onSelected: (value) {
                              if (value == 'edit') _editCharge(charge);
                              if (value == 'delete') _deleteCharge(charge);
                            },
                            itemBuilder: (context) => const [
                              PopupMenuItem(value: 'edit', child: Text('Edit')),
                              PopupMenuItem(
                                value: 'delete',
                                child: Text('Delete',
                                    style: TextStyle(color: Colors.red)),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                  )),
            if (_serviceLines.isNotEmpty || _charges.isNotEmpty) ...[
              const Divider(height: 24),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.end,
                  children: [
                    if (_charges.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(bottom: 4),
                        child: Text(
                          'Services: ${AppUtils.formatCurrency(_serviceLinesTotal)} '
                          '· Travel & Incidentals: ${AppUtils.formatCurrency(_chargesTotal)}',
                          style: Theme.of(context).textTheme.bodySmall,
                        ),
                      ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text('Total',
                            style:
                                Theme.of(context).textTheme.titleLarge?.copyWith(
                                      fontWeight: FontWeight.bold,
                                    )),
                        Text(
                          AppUtils.formatCurrency(_total),
                          style:
                              Theme.of(context).textTheme.titleLarge?.copyWith(
                                    fontWeight: FontWeight.bold,
                                    color: _visit.paid
                                        ? Colors.green
                                        : Theme.of(context).colorScheme.primary,
                                  ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              if (!_visit.paid && _invoices.isEmpty)
                Padding(
                  padding: const EdgeInsets.all(16),
                  child: ElevatedButton.icon(
                    onPressed: _generateInvoice,
                    icon: const Icon(Icons.receipt_long),
                    label: const Text('Generate Invoice'),
                    style: ElevatedButton.styleFrom(
                      minimumSize: const Size(double.infinity, 48),
                    ),
                  ),
                ),
            ],
            const SizedBox(height: 16),
            SectionHeader(
              title: 'Invoice History',
              onAdd: (_serviceLines.isNotEmpty || _charges.isNotEmpty) &&
                      _invoices.isEmpty
                  ? _generateInvoice
                  : null,
              addLabel: 'Create Invoice',
            ),
            if (_invoices.isEmpty)
              Padding(
                padding: const EdgeInsets.all(16),
                child: _serviceLines.isEmpty && _charges.isEmpty
                    ? const Text(
                        'Add service lines or charges before creating an invoice')
                    : ElevatedButton.icon(
                        onPressed: _generateInvoice,
                        icon: const Icon(Icons.receipt_long),
                        label: const Text('Create Invoice'),
                        style: ElevatedButton.styleFrom(
                          minimumSize: const Size(double.infinity, 48),
                        ),
                      ),
              )
            else
              ..._invoices.map(
                (invoice) => Card(
                  margin: const EdgeInsets.symmetric(
                    horizontal: 16,
                    vertical: 4,
                  ),
                  child: ListTile(
                    leading: CircleAvatar(
                      backgroundColor: invoice.paidAt != null
                          ? Colors.green.shade100
                          : Theme.of(context).colorScheme.secondaryContainer,
                      child: Icon(
                        invoice.paidAt != null
                            ? Icons.check_circle
                            : Icons.receipt_long,
                        color: invoice.paidAt != null
                            ? Colors.green
                            : Theme.of(context)
                                .colorScheme
                                .onSecondaryContainer,
                      ),
                    ),
                    title: Text(invoice.invoiceNumber),
                    subtitle: Text(
                      '${AppUtils.formatDate(invoice.issuedAt)} · ${invoice.paidAt != null ? 'Paid' : 'Unpaid'}',
                    ),
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        Text(AppUtils.formatCurrency(invoice.total)),
                        PopupMenuButton<String>(
                          onSelected: (value) {
                            if (value == 'view') _viewInvoice(invoice);
                            if (value == 'share') _shareInvoiceRecord(invoice);
                            if (value == 'print') _printInvoiceRecord(invoice);
                          },
                          itemBuilder: (context) => const [
                            PopupMenuItem(
                              value: 'view',
                              child: Text('View'),
                            ),
                            PopupMenuItem(
                              value: 'share',
                              child: Text('Share'),
                            ),
                            PopupMenuItem(
                              value: 'print',
                              child: Text('Print'),
                            ),
                          ],
                        ),
                      ],
                    ),
                    onTap: () => _viewInvoice(invoice),
                  ),
                ),
              ),
            const SizedBox(height: 16),
            SectionHeader(
              title: 'Photos (${_photos.length})',
              onAdd: _addPhoto,
              addLabel: 'Add Photo',
            ),
            if (_photos.isEmpty)
              const Padding(
                padding: EdgeInsets.all(16),
                child: Text('No photos yet'),
              )
            else
              PhotoGrid(
                photos: _photos,
                onTap: (photo) => _showPhotoFullScreen(photo),
                onLongPress: (photo) => _deletePhoto(photo),
              ),
          ],
        ),
      ),
    );
  }
}
